apiVersion: apps/v1
kind: Deployment
metadata:
  name: p41-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p41-app
  template:
    metadata:
      labels:
        app: p41-app
    spec:
      containers:
      - name: p41-app
        image: aayush303/p41-task:v1
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: p41-service
  namespace: default
spec:
  selector:
    app: p41-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000