FROM python:3.7.3-slim
RUN pip install --upgrade pip
RUN useradd worker
USER worker
WORKDIR /home/worker
COPY --chown=worker:worker requirements.txt requirements.txt
RUN pip install --user -r requirements.txt
ENV PATH="/home/worker/.local/bin:${PATH}"
COPY --chown=worker:worker . .
ENTRYPOINT ["./gunicorn_starter.sh"]